In [1]:
import cv2
import torchvision.transforms as transforms
import torch
import pandas as pd
from os import listdir
from os.path import isfile, join
import sys
import numpy as np
import math

In [10]:
std = 5.135049447870994 / 255.0
mean = 70.71117162231828 / 255.0

t = torch.tensor([[[0, 0.5, 1]]])
t* (std / 0.5) + (mean - 0.5) / 0.5, std, mean, transforms.Normalize(0.5, 0.5)(t)

(tensor([[[-0.4454, -0.4253, -0.4051]]]),
 0.02013744881518037,
 0.2772987122443854,
 tensor([[[-1.,  0.,  1.]]]))

In [79]:
def processImages(img_path,  size_target=256):
    img = cv2.imread(img_path)

    size_target = 450
    img = cv2.resize(img, (size_target, size_target), interpolation=cv2.INTER_LINEAR)

    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    lab_planes = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    lab_planes[0] = clahe.apply(lab_planes[0])
    lab = cv2.merge(lab_planes)
    bgr = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)

    x = y = (size_target - 299) // 2

    h = w = 299
    img = bgr[y:y + h, x:x + w]

    arr = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    t_img = torch.tensor(arr).unsqueeze(0).float()
    return t_img

In [80]:
path_to_data = '/Users/janbraunsdorff/Studienarbeit-projekt/data'
path_to_validation_annotation = path_to_data + "/validation.csv"
path_to_training_annotation = path_to_data + "/training.csv"
path_to_validatoin_data = path_to_data + '/boneage-validation-dataset/'
path_to_training_data = path_to_data + '/boneage-training-dataset/'
path = path_to_data + '/pickel/v3'

In [81]:
count = 0
df_trainig = pd.read_csv(path_to_training_annotation)
for index, row in df_trainig.iterrows():
    img = processImages(path_to_training_data + str(row[0]) + ".png")
    count += torch.mean(img).item()
    if index % 500 == 0:
        print(index)

0
200
400
600
800
1000
1200
1400
1600
1800
2000
2200
2400
2600
2800
3000
3200
3400
3600
3800
4000
4200
4400
4600
4800
5000
5200
5400
5600
5800
6000
6200
6400
6600
6800
7000
7200
7400
7600
7800
8000
8200
8400
8600
8800
9000
9200
9400
9600
9800
10000
10200
10400
10600
10800
11000
11200
11400
11600
11800
12000
12200
12400
12600


In [82]:
mean = count / float(len(df_trainig))

In [83]:
mean, mean / 255.0

(70.71117162231828, 0.2772987122443854)

In [100]:
dic = np.zeros(256, dtype=int)
for counter, row in df_trainig.iterrows():
    img = processImages(path_to_training_data + str(row[0]) + ".png")
    el, count = np.unique(img.numpy(), return_counts=True)
    
    for index, x in np.ndenumerate(el):
        dic[int(x)] += count[index]

    if  counter % 500 == 0:
        print(counter)

0
500
1000
1500
2000
2500
3000
3500
4000
4500
5000
5500
6000
6500
7000
7500
8000
8500
9000
9500
10000
10500
11000
11500
12000
12500


In [114]:
dic = np.array([981 , 0 , 134917 , 3249176 , 34369321 , 0 , 8427264 , 15490469 , 0 , 28061121 , 26439491 , 25438829 , 0 , 23587856 , 25479570 , 29521257 , 28386858 , 21185180 , 16952525 , 13097043 , 9685354 , 6915798 , 5456149 , 8476240 , 3720266 , 7104368 , 3469100 , 3421056 , 3561720 , 7465011 , 3899063 , 3909991 , 4026967 , 4198165 , 9079756 , 5020997 , 5300376 , 5499906 , 12067156 , 6543420 , 6702311 , 7103132 , 7060603 , 14319850 , 7170051 , 6994228 , 6730580 , 6659509 , 12746451 , 6105370 , 6034728 , 6053661 , 11888827 , 5920978 , 5976774 , 6061092 , 6142851 , 6284759 , 6391215 , 12908569 , 6505067 , 6495013 , 6464616 , 6449056 , 6428820 , 6426777 , 6392402 , 12699727 , 6308729 , 6263491 , 6252270 , 6216951 , 6188380 , 6123605 , 6086581 , 6001459 , 5933630 , 11575206 , 5639663 , 5533596 , 5416208 , 5322431 , 5190212 , 5088701 , 4964474 , 4871736 , 4768362 , 4679565 , 4579188 , 4502515 , 8757825 , 4266389 , 4202735 , 4144825 , 4094628 , 4043775 , 4011809 , 3975130 , 3950779 , 3929674 , 3912563 , 3880829 , 3871540 , 3854166 , 3846207 , 3837997 , 3838345 , 3826770 , 3827327 , 3816865 , 3813318 , 3820162 , 7639788 , 0 , 7649451 , 3833380 , 3835789 , 3842361 , 3842378 , 3852875 , 3847960 , 3857690 , 3854600 , 3862187 , 3854648 , 3863823 , 3857572 , 3862416 , 3842507 , 3850839 , 3834297 , 3818836 , 3804190 , 3793330 , 3778116 , 3764622 , 3743424 , 3732046 , 3703255 , 3692271 , 3664161 , 3643126 , 0 , 3613500 , 3596925 , 3564429 , 3542270 , 3508165 , 3479548 , 3449280 , 3418740 , 3381484 , 3351103 , 3313987 , 3280988 , 3235704 , 3199896 , 3154376 , 3117092 , 3072415 , 3034184 , 2991204 , 2948185 , 2900730 , 2855558 , 2805600 , 2759916 , 2711928 , 2663238 , 2605420 , 0 , 2559041 , 2507569 , 2458170 , 2404740 , 2355898 , 2301108 , 2252165 , 2197255 , 2145493 , 2093815 , 2043408 , 1989076 , 1938406 , 1884346 , 1835109 , 1782014 , 0 , 1729976 , 1676458 , 1627070 , 1571715 , 1523304 , 1469536 , 1424966 , 1373122 , 1326949 , 1273412 , 1229069 , 1179943 , 1136376 , 0 , 1087374 , 1045282 , 1000044 , 959083 , 915053 , 875854 , 832401 , 796196 , 755408 , 721940 , 0 , 683989 , 651199 , 618167 , 584442 , 553536 , 523427 , 494202 , 466638 , 437687 , 413162 , 0 , 387197 , 362749 , 341432 , 320418 , 299596 , 281065 , 263443 , 245934 , 230219 , 0 , 216306 , 201571 , 188774 , 175014 , 163838 , 152271 , 141320 , 129969 , 0 , 120236 , 109744 , 99088 , 90121 , 82017 , 71270 , 76602 , 83134 , 0 , 71652 , 51626 , 22532 , 384132])

In [116]:
print(dic, np.sum(dic)== 299*299*12611)

[     981        0   134917  3249176 34369321        0  8427264 15490469
        0 28061121 26439491 25438829        0 23587856 25479570 29521257
 28386858 21185180 16952525 13097043  9685354  6915798  5456149  8476240
  3720266  7104368  3469100  3421056  3561720  7465011  3899063  3909991
  4026967  4198165  9079756  5020997  5300376  5499906 12067156  6543420
  6702311  7103132  7060603 14319850  7170051  6994228  6730580  6659509
 12746451  6105370  6034728  6053661 11888827  5920978  5976774  6061092
  6142851  6284759  6391215 12908569  6505067  6495013  6464616  6449056
  6428820  6426777  6392402 12699727  6308729  6263491  6252270  6216951
  6188380  6123605  6086581  6001459  5933630 11575206  5639663  5533596
  5416208  5322431  5190212  5088701  4964474  4871736  4768362  4679565
  4579188  4502515  8757825  4266389  4202735  4144825  4094628  4043775
  4011809  3975130  3950779  3929674  3912563  3880829  3871540  3854166
  3846207  3837997  3838345  3826770  3827327  3816

In [118]:
dic = dic.astype(float)

In [121]:
dic = dic / float(299*299*12611)

In [123]:
dic

array([8.70115901e-07, 0.00000000e+00, 1.19667102e-04, 2.88191611e-03,
       3.04844982e-02, 0.00000000e+00, 7.47471601e-03, 1.37395549e-02,
       0.00000000e+00, 2.48893247e-02, 2.34509903e-02, 2.25634349e-02,
       0.00000000e+00, 2.09216805e-02, 2.25995708e-02, 2.61844191e-02,
       2.51782431e-02, 1.87905831e-02, 1.50363522e-02, 1.16166619e-02,
       8.59060195e-03, 6.13409358e-03, 4.83943119e-03, 7.51815617e-03,
       3.29975800e-03, 6.30134919e-03, 3.07698172e-03, 3.03436822e-03,
       3.15913273e-03, 6.62122810e-03, 3.45834527e-03, 3.46803806e-03,
       3.57179207e-03, 3.72363927e-03, 8.05345573e-03, 4.45346516e-03,
       4.70126548e-03, 4.87824227e-03, 1.07031848e-02, 5.80380610e-03,
       5.94473738e-03, 6.30025290e-03, 6.26253103e-03, 1.27012530e-02,
       6.35960793e-03, 6.20365851e-03, 5.96981109e-03, 5.90677336e-03,
       1.13056980e-02, 5.41526964e-03, 5.35261242e-03, 5.36940540e-03,
       1.05450127e-02, 5.25171978e-03, 5.30120906e-03, 5.37599646e-03,
      

In [134]:
var = 0.0
for index, row in df_trainig.iterrows():
    img = processImages(path_to_training_data + str(row[0]) + ".png")
    img = img.numpy().squeeze().reshape(299*299)
    for x in img:
        var += math.pow((x - mean),2) * dic[int(x)]
    

    if index % 500 == 0:
        print(index)

0
500
1000
1500
2000
2500
3000
3500
4000
4500
5000
5500
6000
6500
7000
7500
8000
8500
9000
9500
10000
10500
11000
11500
12000
12500


In [139]:
math.sqrt((var / (299*299*12611)))

5.135049447870994

In [135]:
std = math.sqrt(var)

In [136]:
std, mean

(172421.1673760656, 70.71117162231828)

In [74]:

np.unique(dic, )

In [75]:
for index, x in np.ndenumerate(el):
    dic[x] += count[index]
    print('val: ' , x, ' count: ' , count[index])

val:  1  count:  2
val:  2  count:  4
val:  3  count:  3
val:  4  count:  3
val:  5  count:  2
val:  6  count:  4
val:  7  count:  2
val:  8  count:  3
val:  9  count:  3
val:  34  count:  1


In [76]:
dic

array([0., 2., 4., 3., 3., 2., 4., 2., 3., 3., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.